server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label:  config-service
          uri:  https://github.com/sanzlju/config-service
          search-paths: config-data
  application:
    name: config-service



